language: python
python:
  - "2.7"

env:
  - DJANGO="1.4.x" DBENGINE=pg
  - DJANGO="1.5.x" DBENGINE=pg
  - DJANGO="1.6.x" DBENGINE=pg


install:
  - pip install coverage python-coveralls

script:
  - make ci

before_script:
  - make init-db

after_success:
  - coveralls -c .coveragerc

